LoginScreen/LoginScreen/Models/ViewModels/AlterarSenhaViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace LoginScreen.Models.ViewModels
{
    public class AlterarSenhaViewModel
    {
        [Required(ErrorMessage = "É necessário digitar a nova senha")]
        [StringLength(20, MinimumLength = 8, ErrorMessage = "A senha precisa ter entre {2} e {1} caracteres")]
        [DataType(DataType.Password)]
        public string novaSenha { get; set; }
        [Required(ErrorMessage = "É necessário confirmar a nova senha")]
        [StringLength(20, MinimumLength = 8, ErrorMessage = "A senha precisa ter entre {2} e {1} caracteres")]
        [DataType(DataType.Password)]
        [Compare("novaSenha", ErrorMessage ="As senhas não batem")]
        public string confirmarNovaSenha { get; set; }
    }
}

LoginScreen/LoginScreen/Models/ViewModels/RecuperarSenhaViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace LoginScreen.Models.ViewModels
{
    public class RecuperarSenhaViewModel
    {
        [Required(ErrorMessage = "É necessário informar seu email")]
        [DataType(DataType.EmailAddress, ErrorMessage = "O email digitado é inválido")]
        public string email { get; set; }
    }
}

LoginScreen/LoginScreen/Controllers/EntrarController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using LoginScreen.Models;
using LoginScreen.Models.ViewModels;
using LoginScreen.Services;
using System;
using MailKit.Net.Smtp;
using MimeKit;

namespace LoginScreen.Controllers
{
    public class EntrarController : Controller
    {
        private readonly UsuarioServices _usuarioService;

        public EntrarController(UsuarioServices usuarioService)
        {
            _usuarioService = usuarioService;
        }

        public IActionResult Logar()
        {
            TempData["Layout"] = "~/Views/Shared/_Entrar.cshtml";
            TempData["Logado"] = null;
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Logar(LoginViewModel usuario)
        {
            TempData["Layout"] = "~/Views/Shared/_Entrar.cshtml";
            if (_usuarioService.Logar(usuario))
            {
                if (_usuarioService.UsuarioConfirmado(usuario.nomeDeUsuario))
                {
                    TempData["Logado"] = _usuarioService.PegarUsuario(usuario.nomeDeUsuario).id;
                    return RedirectToAction("Principal", "Logado");
                }
                else
                {
                    TempData["IdParaConfirmar"] = _usuarioService.PegarUsuario(usuario.nomeDeUsuario).id;
                    return RedirectToAction(nameof(ConfirmarConta));
                }
                
            }
            ViewData["ErroDeCredencias"] = "Credenciais inválidas";
            return View(usuario);
        }
        public IActionResult Cadastrar()
        {
            TempData["Layout"] = "~/Views/Shared/_Entrar.cshtml";
            TempData["Logado"] = null;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Cadastrar(CadastroViewModel usuario)
        {
            TempData["Layout"] = "~/Views/Shared/_Entrar.cshtml";
            if (ModelState.IsValid)
            {
                if (_usuarioService.PegarIdPorEmail(usuario.email) == 0)
                {
                    int id = _usuarioService.Cadastrar(usuario);
                    if (id != 0)
                    {
                        TempData["IdParaConfirmar"] = id;
                        return RedirectToAction(nameof(ConfirmarConta));
                    }
                    else
                    {
                        ViewData["UsuarioErro"] = "O Nome de usuário em questão já está cadastrado, tente outro";
                        return View(usuario);
                    }
                }
                else
                {
                    ViewData["EmailErro"] = "O email em questão já está cadastrado";
                }
            }
            return View(usuario);
        }
        public IActionResult ConfirmarConta()
        {
            TempData["Layout"] = "~/Views/Shared/_Entrar.cshtml";
            int id = int.Parse(TempData["IdParaConfirmar"].ToString());
            if(id == 0)
            {
                return BadRequest();
            }
            Random rand = new Random();
            int codigo = rand.Next(100000, 999999);
            var message = new MimeMessage();
            message.From.Add(new MailboxAddress("loginscreenconfirmation@gmail.com"));
            message.To.Add(new MailboxAddress(_usuarioService.PegarUsuario(id).email.ToString()));
            message.Subject = "Confirmação da conta";
            message.Body = new TextPart("plain")
            {
                Text = "O código para confirmar a sua conta é " + codigo
            };

            using(var cliente = new SmtpClient())
            {
                cliente.Connect("smtp.gmail.com", 587, false);
                cliente.Authenticate("loginscreenconfirmation@gmail.com", "Adgswasfffcvb_15483286421321058");
                cliente.Send(message);
                cliente.Disconnect(true);
            }
            TempData["IdParaConfirmar"] = id;
            TempData["codigo"] = codigo;
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ConfirmarConta(ConfirmacaoPorEmailViewModel user)
        {
            TempData["Layout"] = "~/Views/Shared/_Entrar.cshtml";
            int id = int.Parse(TempData["IdParaConfirmar"].ToString());
            int codigo = int.Parse(TempData["codigo"].ToString());
            if (user.codigo == codigo)
            {
                _usuarioService.ConfirmarConta(id);
                TempData["Logado"] = id;
                return RedirectToAction("Principal","Logado");
            }
            else
            {
                TempData["id"] = id;
                TempData["codigo"] = codigo;
                ViewBag.codigoInvalido = "O codigo digitado é inválido";
                return View();
            }
        }

        public IActionResult RecuperarSenha()
        {
            TempData["Layout"] = "~/Views/Shared/_Entrar.cshtml";
            TempData["Logado"] = null;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult RecuperarSenha(RecuperarSenhaViewModel usuario)
        {
            TempData["Layout"] = "~/Views/Shared/_Entrar.cshtml";
            if (ModelState.IsValid)
            {
                int id = _usuarioService.PegarIdPorEmail(usuario.email);
                if (id != 0)
                {
                    Random rand = new Random();
                    int codigo = rand.Next(100000, 999999);
                    var message = new MimeMessage();
                    message.From.Add(new MailboxAddress("loginscreenconfirmation@gmail.com"));
                    message.To.Add(new MailboxAddress(_usuarioService.PegarUsuario(id).email.ToString()));
                    message.Subject = "Recuperação de conta";
                    message.Body = new TextPart("plain")
                    {
                        Text = "O código para recuperar sua conta é " + codigo
                    };

                    using (var cliente = new SmtpClient())
                    {
                        cliente.Connect("smtp.gmail.com", 587, false);
                        cliente.Authenticate("loginscreenconfirmation@gmail.com", "Adgswasfffcvb_15483286421321058");
                        cliente.Send(message);
                        cliente.Disconnect(true);
                    }
                    TempData["IdParaRecuperar"] = id;
                    TempData["codigoRecuperar"] = codigo;
                        return RedirectToAction(nameof(ConfirmarRecuperarSenha));
                }
            }
            return View(usuario);
        }
        public IActionResult ConfirmarRecuperarSenha()
        {
            TempData["Layout"] = "~/Views/Shared/_Entrar.cshtml";
            TempData["Logado"] = null;
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ConfirmarRecuperarSenha(ConfirmacaoPorEmailViewModel user)
        {
            TempData["Layout"] = "~/Views/Shared/_Entrar.cshtml";
            int id = int.Parse(TempData["IdParaRecuperar"].ToString());
            if (id == 0)
            {
                return BadRequest();
            }
            int codigo = int.Parse(TempData["codigoRecuperar"].ToString());
            if (ModelState.IsValid)
            {
                if (user.codigo == codigo)
                {
                    TempData["IdParaRecuperar"] = id;
                    return RedirectToAction(nameof(AlterarSenha));
                }
                ViewBag.codigoInvalido = "codigo digitado inválido";
            }
            TempData["IdParaRecuperar"] = id;
            TempData["codigoRecuperar"] = codigo;
            return View();
        }

        public IActionResult AlterarSenha()
        {
            TempData["Layout"] = "~/Views/Shared/_Entrar.cshtml";
            TempData["Logado"] = null;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AlterarSenha(AlterarSenhaViewModel obj)
        {
            TempData["Layout"] = "~/Views/Shared/_Entrar.cshtml";
            int id = int.Parse(TempData["IdParaRecuperar"].ToString());
            if (id == 0)
            {
                return BadRequest();
            }
            if (ModelState.IsValid)
            {
                _usuarioService.AlterarSenha(obj, id);
                return RedirectToAction(nameof(Logar));
            }
            return View();
        }
    }
}

LoginScreen/LoginScreen/Views/Entrar/AlterarSenha.cshtml
@model LoginScreen.Models.ViewModels.AlterarSenhaViewModel
@{
    ViewData["Title"] = "Alterar senha";
}
<div class="container">
    <div class="d-flex justify-content-center">
        <div class="card" id="card-login">
            <div class="card-header" style="text-align:center;">
                <h1 id="tituloPrincipal">@ViewData["title"]</h1>
            </div>
            <div class="card-body">
                <form asp-action="AlterarSenha">

                    <span asp-validation-for="novaSenha" class="text-danger"></span>
                    <div class="input-group form-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-key"></i></span>
                        </div>
                        <input asp-for="novaSenha" type="password" class="form-control" placeholder="Nova senha">
                    </div>

                    <span asp-validation-for="confirmarNovaSenha" class="text-danger"></span>
                    <div class="input-group form-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-key"></i></span>
                        </div>
                        <input asp-for="confirmarNovaSenha" type="password" class="form-control" placeholder="Confirme a nova senha">
                    </div>
                    <div class="form-group d-flex justify-content-center" style="margin-top: 10px;">
                        <input type="submit" value="Alterar" class="btn btn-dark float-right">
                    </div>
                </form>

                <div class="card-footer">
                    <div class="d-flex justify-content-center ">
                        <a asp-action="Logar" class="texto-padrao">Voltar</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LoginScreen/LoginScreen/Views/Entrar/Cadastrar.cshtml
@model LoginScreen.Models.ViewModels.CadastroViewModel
@{
    ViewData["Title"] = "Cadastrar";
}
<div class="container">
    <div class="d-flex justify-content-center">
        <div class="card" id="card-cadastro">
            <div class="card-header" style="text-align:center;">
                <h1 id="tituloPrincipal">Cadastro</h1>
            </div>
            <div class="card-body">
                <form asp-action="Cadastrar">
                    <span class="text-danger">@ViewData["UsuarioErro"]</span>
                    <span asp-validation-for="nomeDeUsuario" class="text-danger"></span>
                    <div class="input-group form-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fa fa-user"></i></span>
                        </div>
                        <input asp-for="nomeDeUsuario" type="text" class="form-control" placeholder="Nome de usuário" />
                    </div>

                    <span asp-validation-for="nome" class="text-danger"></span>
                    <div class="input-group form-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fa fa-id-card"></i></span>
                        </div>
                        <input asp-for="nome" type="text" class="form-control" placeholder="Nome" />
                    </div>

                    <span class="text-danger">@ViewData["EmailErro"]</span>
                    <span asp-validation-for="email" class="text-danger"></span>
                    <div class="input-group form-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fa fa-envelope-square"></i></span>
                        </div>
                        <input asp-for="email" type="email" class="form-control" placeholder="Email" />
                    </div>

                    <span asp-validation-for="senha" class="text-danger"></span>
                    <div class="input-group form-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-key"></i></span>
                        </div>
                        <input asp-for="senha" type="password" class="form-control" placeholder="Senha">
                    </div>

                    <span asp-validation-for="confirmarSenha" class="text-danger"></span>
                    <div class="input-group form-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-key"></i></span>
                        </div>
                        <input asp-for="confirmarSenha" type="password" class="form-control" placeholder="Confirme a senha">
                    </div>
                    <div class="form-group d-flex justify-content-center" style="margin-top: 10px;">
                        <input type="submit" value="Cadastrar" class="btn btn-dark float-right">
                    </div>
                </form>

                <div class="card-footer">
                    <div class="d-flex justify-content-center ">
                        <a asp-action="Logar" class="texto-padrao">Voltar</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LoginScreen/LoginScreen/Views/Entrar/ConfirmarConta.cshtml
@model LoginScreen.Models.ViewModels.ConfirmacaoPorEmailViewModel
@{
    ViewData["Title"] = "Confirmar conta";
}

<div class="container">
    <div class="d-flex justify-content-center">
        <div class="card" id="card-login">
            <div class="card-header" style="text-align:center;">
                <h1 id="tituloPrincipal">@ViewData["Title"]</h1>
            </div>
            <div class="card-body">
                <form asp-action="ConfirmarConta" method="post">
                    <span style="text-align:center;" class="texto-padrao"></span>
                    <span class="text-danger">@ViewBag.codigoInvalido</span>
                    <span asp-validation-for="codigo" class="text-danger"></span>
                    <div class="input-group form-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-barcode"></i></span>
                        </div>
                        <input asp-for="codigo" class="form-control" placeholder="Código enviado" />
                    </div>
                    <div class="form-group d-flex justify-content-center" style="margin-top: 10px;">
                        <input type="submit" value="Confirmar" class="btn btn-dark float-right">
                    </div>
                </form>
                <div class="card-footer">
                    <div class="d-flex justify-content-center ">
                        <a asp-action="Logar" class="texto-padrao">Voltar</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LoginScreen/LoginScreen/Views/Entrar/ConfirmarRecuperarSenha.cshtml
@model LoginScreen.Models.ViewModels.ConfirmacaoPorEmailViewModel
@{
    ViewData["Title"] = "Recuperar senha";
}

<div class="container">
    <div class="d-flex justify-content-center">
        <div class="card" id="card-login">
            <div class="card-header" style="text-align:center;">
                <h1 id="tituloPrincipal">@ViewData["Title"]</h1>
            </div>
            <div class="card-body">
                <form asp-action="ConfirmarRecuperarSenha" method="post">
                    <span style="text-align:center;" class="texto-padrao"></span>
                    <span class="text-danger">@ViewBag.codigoInvalido</span>
                    <span asp-validation-for="codigo" class="text-danger"></span>
                    <div class="input-group form-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-barcode"></i></span>
                        </div>
                        <input asp-for="codigo" class="form-control" placeholder="Código enviado" />
                    </div>
                    <div class="form-group d-flex justify-content-center" style="margin-top: 10px;">
                        <input type="submit" value="Confirmar" class="btn btn-dark float-right">
                    </div>
                </form>
                <div class="card-footer">
                    <div class="d-flex justify-content-center ">
                        <a asp-action="Logar" class="texto-padrao">Voltar</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LoginScreen/LoginScreen/Views/Entrar/Logar.cshtml
@model LoginScreen.Models.ViewModels.LoginViewModel
@{
    ViewData["Title"] = "Logar";
}

<div class="container">
    <div class="d-flex justify-content-center">
        <div class="card" id="card-login">
            <div class="card-header" style="text-align:center;">
                <h1 id="tituloPrincipal">Entrar</h1>
            </div>
            <div class="card-body">
                <form asp-action="Logar">
                    <div class="text-danger">@ViewData["ErroDeCredencias"]</div>
                    <div class="text-success">@ViewData["message"]</div>
                    <span asp-validation-for="nomeDeUsuario" class="text-danger"></span>
                    <div class="input-group form-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fa fa-user"></i></span>
                        </div>
                        <input asp-for="nomeDeUsuario" type="text" class="form-control" placeholder="Nome de usuário" />
                    </div>
                    <span asp-validation-for="senha" class="text-danger"></span>
                    <div class="input-group form-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-key"></i></span>
                        </div>
                        <input asp-for="senha" type="password" class="form-control" placeholder="Senha">
                    </div>
                    <div class="form-group d-flex justify-content-center" style="margin-top: 10px;">
                        <input type="submit" value="entrar" class="btn btn-dark float-right">
                    </div>
                </form>
                <div class="card-footer">
                    <div class="d-flex justify-content-center ">
                        <a asp-controller="Entrar" asp-action="Cadastrar" class="texto-padrao">Cadastrar</a>
                    </div>
                    <div class="d-flex justify-content-center">
                        <a asp-controller="Entrar" asp-action="RecuperarSenha" class="texto-padrao">Esqueci minha senha</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LoginScreen/LoginScreen/Views/Entrar/RecuperarSenha.cshtml
@model LoginScreen.Models.ViewModels.RecuperarSenhaViewModel
@{
    ViewData["Title"] = "Recuperar senha";
}

<div class="container">
    <div class="d-flex justify-content-center">
        <div class="card" id="card-login">
            <div class="card-header" style="text-align:center;">
                <h1 id="tituloPrincipal">Recuperar senha</h1>
            </div>
            <div class="card-body">
                <form asp-action="RecuperarSenha">
                    <span asp-validation-for="email" class="text-danger"></span>
                    <div class="input-group form-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fa fa-envelope-square"></i></span>
                        </div>
                        <input asp-for="email" type="text" class="form-control" placeholder="Digite o email" />
                    </div>
                    <div class="form-group d-flex justify-content-center" style="margin-top: 10px;">
                        <input type="submit" value="Recuperar" class="btn btn-dark float-right">
                    </div>
                </form>
                <div class="card-footer">
                    <div class="d-flex justify-content-center ">
                        <a asp-action="Logar" class="texto-padrao">Voltar</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}